name: catchmflixx
description: "catchmflixx application"

publish_to: "none"
version: 2.0.5  #1.2.1 16

environment:
    sdk: ">=3.4.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    firebase_core: ^3.2.0
    screen_protector: ^1.4.2
    flutter_riverpod: ^2.5.1
    riverpod_annotation: ^2.3.5
    flutter_localizations:
        sdk: flutter
    page_transition: ^2.1.0
    flutter_animate: ^4.5.0
    shimmer: ^3.0.0
    flutter_svg: ^2.0.10+1
    fluttertoast: ^8.2.6
    shared_preferences: ^2.2.3
    dio: ^5.5.0+1
    cookie_jar: ^4.0.8
    device_info_plus: ^10.1.0
    path_provider: ^2.1.3
    dio_cookie_manager: ^3.1.1
    intl: ^0.19.0
    phosphor_flutter: ^2.1.0
    vibration: ^1.9.0
    cached_network_image: ^3.3.1
    video_player: ^2.9.1
    wakelock_plus: ^1.2.5
    flutter_otp_text_field: ^1.1.3+2
    restart_app: ^1.2.1
    flutter_slidable: ^3.1.1
    url_launcher: ^6.3.0
    cupertino_icons: ^1.0.8
    haptic_feedback: ^0.5.1+1
    firebase_messaging: ^15.0.4
    flutter_displaymode: ^0.6.0
    go_router: ^14.2.3
    webview_flutter: ^4.10.0
    share_plus: ^10.0.0
    upgrader: ^10.3.0
    google_sign_in: ^6.2.1
    firebase_auth: ^5.3.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
    custom_lint: ^0.6.4
    riverpod_lint: ^2.3.10
    riverpod_generator: ^2.4.0

flutter:
    generate: true
    uses-material-design: true
    assets:
        - lib/assets/
        - lib/assets/designs/

    fonts:
        - family: Kollektif
          fonts:
              - asset: lib/fonts/Kollektif.ttf
              - asset: lib/fonts/Kollektif-Italic.ttf
                style: italic
              - asset: lib/fonts/Kollektif-Bold.ttf
                weight: 800
